version: '3'

services:
  
  apache:
    image: ${PROJECT_NAME}/apache
    container_name: ${PROJECT_NAME}-apache
    build:
      context: "./apache"
      dockerfile: "Dockerfile"
    ports:
     - "80:80"
     - "443:443"
    restart: always
    volumes:
     - ./apache/conf:/usr/local/apache2/conf
     - ./apache/conf.d:/usr/local/apache2/conf.d
     - ./apache/ssl:/usr/local/apache2/ssl
     - ./apache/logs:/usr/local/apache2/logs
     - ../public:/var/www/html
